[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_tickets = "UdaXXAyGLw94jH4e3nqFmHdkKvPe1rgUxi9h8N1V4cT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
[test]
startup_wait = 10000
[test.validator]
url = "https://api.devnet.solana.com"
clone = [
    { address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" }  # Metaplex Token Metadata
]
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
